In [ ]:
## Exercicio de LAB 06 Curso Banco de Dados - FATEC SJC

## Importando biblioteca Pandas
import pandas as pd

# Define o tipo para a coluna diagnosis
DTYPES = {'App': str}

## Importando arquivo salvo no github para analise
url = 'https://github.com/MaXximiles/LAB06/raw/main/Data/Ar%20india%20station_day.csv'

## Lendo os dados separados por virgula
wbc= pd.read_csv(url, sep=',', header=0, dtype = DTYPES)

## Exibindo primeiros 5 registros
wbc.head(25)

## Vendo informações da base de dados
wbc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108035 entries, 0 to 108034
Data columns (total 16 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   StationId   108035 non-null  object
 1   Date        108035 non-null  object
 2   PM2.5       86410 non-null   float64
 3   PM10        65329 non-null   float64
 4   NO          90929 non-null   float64
 5   NO2         91488 non-null   float64
 6   NOx         92535 non-null   float64
 7   NH3         59930 non-null   float64
 8   CO          95037 non-null   float64
 9   SO2         82831 non-null   float64
 10  O3          82467 non-null   float64
 11  Benzene     76580 non-null   float64
 12  Toluene     69333 non-null   float64
 13  Xylene      22898 non-null   float64
 14  AQI         87025 non-null   float64
 15  AQI_Bucket  87025 non-null   object
dtypes: float64(13), object(3)
memory usage: 13.2+ MB

In [ ]:
## Limpando Dados nulos
wbc.dropna(inplace=True)

## Exibindo primeiros 5 registros
wbc.head(5)

,StationId,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
1,AP001,2017-11-25,81.40,124.50,1.44,20.50,12.08,10.72,0.12,15.24,127.09,0.20,6.50,0.06,184.0,4.0
2,AP001,2017-11-26,78.32,129.06,1.26,26.00,14.85,10.28,0.14,26.96,117.44,0.22,7.95,0.08,197.0,4.0
3,AP001,2017-11-27,88.76,135.32,6.60,30.85,21.77,12.91,0.11,33.59,111.81,0.29,7.63,0.12,198.0,4.0
4,AP001,2017-11-28,64.18,104.09,2.56,28.07,17.01,11.42,0.09,19.00,138.18,0.17,5.02,0.07,188.0,4.0
5,AP001,2017-11-29,72.47,114.84,5.23,23.20,16.59,12.25,0.16,10.55,109.74,0.21,4.71,0.08,173.0,4.0

In [ ]:
wbc['AQI_Bucket'] = wbc['AQI_Bucket'].replace("Severe",1)
wbc['AQI_Bucket'] = wbc['AQI_Bucket'].replace("Very Poor",2)
wbc['AQI_Bucket'] = wbc['AQI_Bucket'].replace("Poor",3)
wbc['AQI_Bucket'] = wbc['AQI_Bucket'].replace("Moderate",4)
wbc['AQI_Bucket'] = wbc['AQI_Bucket'].replace("Satisfactory",5)
wbc['AQI_Bucket'] = wbc['AQI_Bucket'].replace("Good",6)
wbc['AQI_Bucket'] = wbc['AQI_Bucket'].astype("float")
wbc

,StationId,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
1,AP001,2017-11-25,81.40,124.50,1.44,20.50,12.08,10.72,0.12,15.24,127.09,0.20,6.50,0.06,184.0,4.0
2,AP001,2017-11-26,78.32,129.06,1.26,26.00,14.85,10.28,0.14,26.96,117.44,0.22,7.95,0.08,197.0,4.0
3,AP001,2017-11-27,88.76,135.32,6.60,30.85,21.77,12.91,0.11,33.59,111.81,0.29,7.63,0.12,198.0,4.0
4,AP001,2017-11-28,64.18,104.09,2.56,28.07,17.01,11.42,0.09,19.00,138.18,0.17,5.02,0.07,188.0,4.0
5,AP001,2017-11-29,72.47,114.84,5.23,23.20,16.59,12.25,0.16,10.55,109.74,0.21,4.71,0.08,173.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106143,WB010,2020-02-10,80.93,174.84,82.96,56.74,139.70,29.32,1.18,9.36,15.96,53.71,51.38,1.30,179.0,4.0
106144,WB010,2020-02-11,103.75,217.89,139.58,63.28,181.55,27.56,1.71,11.43,24.75,53.58,55.10,2.29,226.0,3.0
106145,WB010,2020-02-12,115.40,225.76,193.19,70.41,213.77,35.25,2.11,10.49,22.11,58.61,61.42,3.20,259.0,3.0
106146,WB010,2020-02-13,97.37,179.87,105.12,64.34,169.46,36.24,1.51,6.90,12.55,64.90,62.12,2.16,250.0,3.0
106147,WB010,2020-02-14,89.13,179.89,78.47,56.37,134.84,37.98,1.30,8.13,23.21,69.67,66.15,2.42,223.0,3.0

In [ ]:
## Variavel Alvo e Dados
y = wbc['AQI_Bucket']
x = wbc.drop(['AQI_Bucket', 'StationId', 'Date'], axis = 1) ## Armazenando tabela sem coluna Potability

x.head()

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI
1,81.40,124.50,1.44,20.50,12.08,10.72,0.12,15.24,127.09,0.20,6.50,0.06,184.0
2,78.32,129.06,1.26,26.00,14.85,10.28,0.14,26.96,117.44,0.22,7.95,0.08,197.0
3,88.76,135.32,6.60,30.85,21.77,12.91,0.11,33.59,111.81,0.29,7.63,0.12,198.0
4,64.18,104.09,2.56,28.07,17.01,11.42,0.09,19.00,138.18,0.17,5.02,0.07,188.0
5,72.47,114.84,5.23,23.20,16.59,12.25,0.16,10.55,109.74,0.21,4.71,0.08,173.0

In [ ]:
## Importando bilioteca para corte de dados e teste
from sklearn.model_selection import train_test_split

## Sintaxe train_test_split(Dados(planilha), coluna(alvo) test_size = porcentagem de dados para o teste)
## Divide em x teste e treino e y teste e treino
xTreino, xTeste, yTreino, yTeste = train_test_split(x,y,test_size = 0.5)

In [ ]:
## Treinando os Dados: DecisionTreeClassifier(Arvore de Decisão)
from sklearn.tree import DecisionTreeClassifier

## Criação da arvore: 
modelo = DecisionTreeClassifier(max_depth=4, random_state=20)

## Treino da arvore
modelo.fit(xTreino, yTreino)

## Mostrando resultado do treino
resultado = modelo.score(xTeste, yTeste)
print("Acuracia: ", resultado)

Acuracia:  1.0

In [ ]:
yTeste[100:110]

80014     4.0
105384    4.0
85141     4.0
86470     6.0
2164      4.0
1046      4.0
105238    4.0
3075      4.0
91093     4.0
84629     3.0
Name: AQI_Bucket, dtype: float64

In [ ]:
xTeste[100:110]

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI
80014,26.40,83.14,19.15,12.31,29.03,12.12,0.62,11.35,30.35,1.53,1.92,2.00,108.0
105384,19.18,49.09,5.41,11.18,16.59,23.64,0.30,10.90,64.93,2.64,14.73,0.47,105.0
85141,28.42,90.75,2.64,31.45,18.87,10.09,0.59,4.57,81.49,2.29,6.69,1.76,130.0
86470,7.60,12.30,1.33,3.16,2.84,4.14,0.17,6.41,19.38,0.00,0.00,0.00,27.0
2164,116.65,192.80,32.30,41.26,47.34,4.86,1.11,26.63,22.50,1.27,5.51,1.25,132.0
1046,44.10,93.36,24.07,45.35,41.13,14.02,1.03,24.17,25.85,6.30,14.84,7.33,104.0
105238,29.14,52.12,7.19,4.91,11.95,10.07,0.52,7.90,63.47,2.73,20.19,0.60,115.0
3075,52.96,165.61,7.22,9.00,15.22,13.42,0.62,11.20,3.20,0.00,0.00,0.00,123.0
91093,70.88,145.83,14.60,59.88,43.72,23.74,0.94,3.81,37.95,5.45,46.59,17.30,139.0
84629,62.52,114.17,5.82,65.14,39.40,22.53,1.42,17.90,79.09,11.78,31.27,19.30,239.0

In [ ]:
previsao = modelo.predict(xTeste[100:110])
previsao

array([4., 4., 4., 6., 4., 4., 4., 4., 4., 3.])

In [ ]:
#Visualização gráfica da árvore de decisão
import os
from graphviz import Source
from sklearn.tree import export_graphviz

headers = ['PM2.5',	'PM10',	'NO',	'NO2',	'NOx',	'NH3',	'CO',	'SO2',	'O3',	'Benzene',	'Toluene',	'Xylene',	'AQI']

export_graphviz(modelo,
                out_file='AguaparaConsumo', #Arquivo para armazenamento do modelo gráfico
                feature_names=headers[0:13], #Nomes dos atributos
                rounded=True,
                filled=True
                )

#Uso do arquivo gerado para visualizar a árvore
Source.from_file('AguaparaConsumo')